### ISSUE TITLE
Coupla connects

### ISSUE THREAD

**Issue by omightytimm** [vgXhc/city_tax_dashboard#2]
1. Kudos, this is wonderful. The remaining comments/issues are minor
2. Clicking the GitHub issue link in Android Chrome gives an error 
3. (Website comment, not code) Would be better if you emphasized that percentage increases agree year on year, it's not immediately apparent and for my house (3650 ice age Dr) assessed make exponential increase made it look cumulative (and good grief, no wonder affordability is an issue) 

Again, awesome job.

**Comment by vgXhc** [comment]
Thanks for the feedback. 2 should be fixed with e568ff3 (had to do with with a masked redirect, I think), and I also made the links open in a new window.
3 I added a note that the change shown on the charts is year-over-year. I _think_ that's what your comment was about? If not, can you please explain again?

**Comment by omightytimm** [comment]
Yes that's what my comment was about. I had to look at the table data to
convince myself that it was year over year.
